services:
  fitness-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    volumes:
      - c:/data:/var/opt/mssql/data
      - c:/log:/var/opt/mssql/log
      - c:/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Developer
    restart: unless-stopped
    ports:
      - "1433:1433"
  fitness-blob:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: fitness-blob
    ports:
      - "10000:10000" 
      - "10001:10001"
      - "10002:10002"